AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Digital Identity serverless frontend firebreak 🔥"

Resources:

  FirebreakServerlessFrontend:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/versionOne
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - AWSLambdaBasicExecutionRole

  # API Gateway
  FirebreakApiGatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: FirebreakApiGatewayApi
  ServerApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FirebreakApiGatewayApi
      ParentId: !GetAtt FirebreakApiGatewayApi.RootResourceId
      PathPart: '{proxy+}'
  ServerApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId: !Ref ServerApiResource
      RestApiId: !Ref FirebreakApiGatewayApi
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: ANY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FirebreakServerlessFrontend.Arn}/invocations'
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
  ServerApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref FirebreakApiGatewayApi
      StageName: Prod
    DependsOn: ServerApiMethod

  FirebreakServerlessFrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FirebreakServerlessFrontend}"
      RetentionInDays: 30


Outputs:
  ServerlessUrl:
    Description: Url to invoke the serverless Frontend
    Value: !Sub https://${FirebreakApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/