AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Digital Identity serverless frontend firebreak 🔥"

Resources:

  FirebreakServerlessFrontend:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/versionOne
      Handler: app.handler
      Runtime: nodejs16.x
      Timeout: 300
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExpressApi


  # API Gateway
  ExpressApi:
    Type: AWS::Serverless::HttpApi

  FirebreakServerlessFrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FirebreakServerlessFrontend}"
      RetentionInDays: 30


Outputs:
  ServerlessUrl:
    Description: Url to invoke the serverless Frontend
    Value: !Sub https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/